FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y docker.io && rm -rf /var/lib/apt/lists/*

COPY . .

RUN pip install kafka-python fastapi uvicorn pydantic

CMD ["python", "consumer.py"]
